In [15]:
# create 2D numpy array 
import numpy as np 

# create a list 
a = [[11,12,13],[21,22,23],[31,32,33]]
print(a)

# change into numpy array 
A = np.array(a)
print(A)

# dimensions, shape, size  
print(A.ndim, A.shape, A.size)

# Access the element on the second row and third column 
print(A[1,2])

print(A[1],[2])

# Access the element on the first row and first and second columns
print(A[0][0:2])

# Access the element on the first and second rows and third column
print(A[0:2, 2])

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]
[[11 12 13]
 [21 22 23]
 [31 32 33]]
2 (3, 3) 9
23
[21 22 23] [2]
[11 12]
[13 23]


In [21]:
# create a numpy array 

X = np.array([[1,0], [0,1]])
Y = np.array([[2, 1], [1, 2]]) 
Z = X + Y
print(Z)

F = X*Y
print(F)

[[3 1]
 [1 3]]
[[2 0]
 [0 2]]


In [20]:
Y = np.array([[2, 1], [1, 2]]) 
K = 2*Y
print(K)

[[4 2]
 [2 4]]


In [24]:
# Matrix 

A = np.array([[0,1,1],[1,0,1]])
B = np.array([[1,1],[1,1],[-1,1]])
Z = np.dot(A,B)
print(Z)

print(np.sin(Z))

[[0 2]
 [0 2]]
[[0.         0.90929743]
 [0.         0.90929743]]


In [25]:
# transposed of C 
C = np.array([[1,1],[2,2],[3,3]])
print(C.T)

[[1 2 3]
 [1 2 3]]


In [33]:
# Quiz
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A = np.array(a)
print(A)

print(A.size)

print(A[0][0:2])

B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])
X = np.dot(A,B)
print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
[1 2]
[[ 1  4]
 [ 5 12]
 [ 9 20]]
