In [11]:
# matrix multiplication 


### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix mutliplication (dot product)

In [12]:
import torch 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt  
print(torch.__vision__)

# Element wise mul 
tensor = ([1,2,3])
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

ImportError: cannot import name 'Cycler' from 'cycler' (unknown location)

In [ ]:
# matrix mnul 
torch.matmul(tensor, tensor )

In [ ]:
# positional min and max 
x = tensor([1,2,3])
x.argmin()
x.argmax()
x[0]

In [13]:
# reshaping stacking squeezing and unsqueezing tensors 
# indexing 

import torch 
x = torch.arange(1,10).reshape(1, 3, 3) # 1개의 3x3 배열 고로 3차원임. 
x, x.shape

# Let's index on our new tensor
x[0] # 이 표현은 첫 번째 차원에서 첫 번째 요소(인덱스 0)를 선택해. 
# x[0]은 1개의 3x3 행렬을 반환하므로, 2차원 텐서가 돼. 
# tensor([[1, 2, 3],
#         [4, 5, 6],
#         [7, 8, 9]])

# Let's index on the middle bracket (dim=1) 
x[0][0] # 1차에서 전체 선택 후에 2차원에서 첫 행이 선택됨. row.  

# Let's index on the most inner bracket (last dimension)
x[0][1][1]

# You can also use ":" to select "all" of a target dimension
x[:, 0]


# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


In [14]:
import torch 
# create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3876, 0.7545, 0.8934, 0.4389],
        [0.4178, 0.2897, 0.1859, 0.8061],
        [0.3380, 0.8171, 0.6621, 0.3040]])
tensor([[0.7021, 0.6882, 0.5351, 0.5179],
        [0.6662, 0.7696, 0.1661, 0.1676],
        [0.4433, 0.3399, 0.8265, 0.5079]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [16]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [17]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False