In [4]:
# Section1-1 n차원 배열(narray) 생성하기 

import numpy as np

# 1차원 배열 
arr = np.array([1,2,3])

print(arr)

# 2차원 배열 
arr2 = np.array([[1,2,3],
                 [4,5,6]])

print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [6]:
# numpy arry와 리스트는 다르다. 

type([1,2,3])
type(arr)

numpy.ndarray

In [9]:
# 튜플을 바로 np array로 
tpl = (4,5,6)
arr = np.array(tpl)
print(arr)

# 리스트를 바로 np array로
lst = [1,2,3] 
arr = np.array(lst)
print(arr)

# 리스트로 2차원 array
lst2 = [[1,2,3],[4,5,6]]
arr2 = np.array(lst2)
print(arr2)

[4 5 6]
[1 2 3]
[[1 2 3]
 [4 5 6]]


In [15]:
# shape 각 배열의 차원의 크기 / 제일 중요하다. 
arr1 = np.array([1,2,4])
arr2 = np.array([[1,2,3],[4,5,6]])

print(arr1.shape)
print(arr2.shape)

print(arr1.shape, arr2.shape)

# ndim 차원을 알려준다. 
print(arr1.ndim, arr2.ndim)

# 사이즈는 전체 원소 갯수를 알려준다. 
print(arr1.size, arr2.size)


(3,)
(2, 3)
(3,) (2, 3)
1 2
3 6
