In [1]:
# Section1-1 n차원 배열(narray) 생성하기 

import numpy as np

# 1차원 배열 
arr = np.array([1,2,3])

print(arr)

# 2차원 배열 
arr2 = np.array([[1,2,3],
                 [4,5,6]])

print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [2]:
# numpy arry와 리스트는 다르다. 

type([1,2,3])
type(arr)

numpy.ndarray

In [3]:
# 튜플을 바로 np array로 
tpl = (4,5,6)
arr = np.array(tpl)
print(arr)

# 리스트를 바로 np array로
lst = [1,2,3] 
arr = np.array(lst)
print(arr)

# 리스트로 2차원 array
lst2 = [[1,2,3],[4,5,6]]
arr2 = np.array(lst2)
print(arr2)

[4 5 6]
[1 2 3]
[[1 2 3]
 [4 5 6]]


In [4]:
# shape 각 배열의 차원의 크기 / 제일 중요하다. 
arr1 = np.array([1,2,4])
arr2 = np.array([[1,2,3],[4,5,6]])

print(arr1.shape)
print(arr2.shape)

print(arr1.shape, arr2.shape)

# ndim 차원을 알려준다. 
print(arr1.ndim, arr2.ndim)

# 사이즈는 전체 원소 갯수를 알려준다. 
print(arr1.size, arr2.size)


(3,)
(2, 3)
(3,) (2, 3)
1 2
3 6


In [5]:
# 1-2 N차원 배열의 데이터 타입 

arr1 = np.array([1,2,3], dtype=float)
print(arr1, arr1.dtype)

arr2 = np.array([1.1,2.4,3.7], dtype=int)
print(arr2, arr2.dtype)

# bool 데이터 타입은 0 false, 1 true 
arr3 = np.array([0,1,1,0], dtype=bool)
print(arr3, arr3.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[False  True  True False] bool


In [6]:
# 기존에 있던 데이터 타입을 변형하려면, astype을 쓰면 됩니다. 
# 먼저 1차원 어레이 함 만들어 볼게요. 
arr4 = np.array([0,1,2,3])
print(arr,arr.dtype)

arr = arr.astype(np.float32) # 32로 변경된 것을 볼 수 있습니다. 
print(arr, arr.dtype)

[1 2 3] int32
[1. 2. 3.] float32


In [7]:
# 데이터 타입이 혼재하는 경우 
arr = np.array([1,2,3.4,'45']) # 맨 마지막 데이터 기준으로 데이터 타입이 바뀜. 
print(arr,arr.dtype) # U32는 유니코드 형식으로 바뀌었다는걸 말함. 

arr = np.array([1,2,3.4,'45'], dtype = int) # 데이터 타입을 정수형으로 바꿔봄. 
print(arr,arr.dtype) # 근데 중간 문자열이 진짜 글자면 에러남. 

['1' '2' '3.4' '45'] <U32
[ 1  2  3 45] int32


In [8]:
# 1-3 정해진형식의 n 차원 배열 생성하기 
# np.zeroes()
arr = np.zeros([2,2], dtype= int) # argument로 shape을 넣었다. 2행 2열
print(arr)

# np.ones()
arr = np.ones([3,5], dtype = int)
print(arr)

# np.full() 정해진 숫자로 가득채움. 
arr = np.full((2,3),5, dtype = float)
print(arr)

# np.eye()
arr = np.eye(3,4,k=1, dtype = int)
print(arr)

[[0 0]
 [0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[5. 5. 5.]
 [5. 5. 5.]]
[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [9]:
# np.zeroes_like() 원래의 배열과 동일한 쉐입의 배열을 만들어 보자. 
arr = np.array([[1,2,3],
               [4,5,6]])

# np.zeroes_like()
arr_z = np.zeros_like(arr)
print(arr_z)

# np.ones_like()
arr_z = np.ones_like(arr)
print(arr_z)

# np.full_like()
arr_z = np.full_like(arr,7)
print(arr_z)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[7 7 7]
 [7 7 7]]


In [10]:
# 1-4 특정범위의 값을 가지는 N차원 배열 생성하기 
# np.arange()
lst = list(range(0,9,2)) # 0에서 9까지 2칸씩
print(lst)

arr = np.arange(0,9,2) 
print(arr)

arr = np.arange(stop = 9, start =0, step =3) 
print(arr)


# np.linspace()
arr = np.linspace(0,100,250, dtype=int) # n개의 원소를 0-100까지 균등하게 해서 내 뱉음. step이랑 다른 개념 
print(arr)

# np.logspace() 로그 값 스케일의 린 스페이스 메소그 
arr = np.logspace(0,100,2, dtype=int) 
print(arr)

[0, 2, 4, 6, 8]
[0 2 4 6 8]
[0 3 6]
[  0   0   0   1   1   2   2   2   3   3   4   4   4   5   5   6   6   6
   7   7   8   8   8   9   9  10  10  10  11  11  12  12  12  13  13  14
  14  14  15  15  16  16  16  17  17  18  18  18  19  19  20  20  20  21
  21  22  22  22  23  23  24  24  24  25  25  26  26  26  27  27  28  28
  28  29  29  30  30  30  31  31  32  32  32  33  33  34  34  34  35  35
  36  36  36  37  37  38  38  38  39  39  40  40  40  41  41  42  42  42
  43  43  44  44  44  45  45  46  46  46  47  47  48  48  48  49  49  50
  50  51  51  51  52  52  53  53  53  54  54  55  55  55  56  56  57  57
  57  58  58  59  59  59  60  60  61  61  61  62  62  63  63  63  64  64
  65  65  65  66  66  67  67  67  68  68  69  69  69  70  70  71  71  71
  72  72  73  73  73  74  74  75  75  75  76  76  77  77  77  78  78  79
  79  79  80  80  81  81  81  82  82  83  83  83  84  84  85  85  85  86
  86  87  87  87  88  88  89  89  89  90  90  91  91  91  92  92  93  93
  93  94  94  9

c:\Users\qkim8\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\function_base.py:299: RuntimeWarning: invalid value encountered in cast
  return _nx.power(base, y).astype(dtype, copy=False)


In [11]:
arr = np.linspace(1,10,10,dtype=int)
print(arr, end='\n\n')
arr = np.logspace(1,10,10,base=2, dtype=int) # 베이스 지정안하면, 상용 로그로 출력한다. # 로그값 스페이스, 로그 밑, 상용로드 개념 필수 
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]

[   2    4    8   16   32   64  128  256  512 1024]


In [12]:
# 1-5 난수로 이루어진 N차원 배열 생성하기 
# 난수는 random 값 

import matplotlib.pyplot as plt 

# 평균이 0, 표준 편차가 1인 정규 분포에서 10개의 표본을 추출
samples = np.random.normal(0, 1, 10)
print(samples)

samples = np.random.normal(0, 1,(2,3)) # size 부분을 shape으로 변경
print(samples) # 결과가 2,3으로 나오게 됨. 

[-0.55253916  1.43439013 -0.2245877  -1.12847386  1.1443141   0.09296662
 -0.9471624   0.67325838 -0.446253    0.8017625 ]
[[ 0.95662345 -0.03488801  1.55340174]
 [ 0.10743542 -0.61142525  0.72316702]]


In [13]:
# 1-6 Seed값을 통한 난수 생성 제어 