In [6]:
import numpy as np
# N차원 배열 연산법 
# 3-1 배열의 연산 1 : 연산하려면 shape이 같아야함. 브로드캐스팅 쓰면 안같아도 됨. 

arr1 = np.array([[1,2,3],
                [4,5,6]])

arr2 = np.array([[2,2,2],
                [2,2,2]])

print(arr1)
print(arr2)

# +
print(arr1 + arr2)

# 제곱 
print(np.square(arr1))

# 제곱근 
print(np.sqrt(arr1))

[[1 2 3]
 [4 5 6]]
[[2 2 2]
 [2 2 2]]
[[3 4 5]
 [6 7 8]]
[[ 1  4  9]
 [16 25 36]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [12]:
# N차원 배열 연산법 
# 3-1 배열의 연산 2 : dot product/ 절댓값/ 올림 / 내림 / 반올림 / 버림 

# 1차원 행렬 
arr1 = np.array([2,3,4])
arr2 = np.array([1,2,3])

print(np.dot(arr1,arr2)) # 각각 원소의 곱의 합

# 2차원 행렬 

arr1 = np.array([[1,2],
                [3,4]])

arr2 = np.array([[2,2],
                [2,2]])

print(np.dot(arr1,arr2))


20
[[ 6  6]
 [14 14]]


In [14]:
# 절댓값

arr1 = np.array([[1,-2],
                [3,4]])

print(np.abs(arr1))

[[1 2]
 [3 4]]


In [21]:
# 올림

arr1 = np.array([[1.5,-2.87],
                [3,4]])

print(np.ceil(arr1))

# 내림 
print(np.floor(arr1))

# 반올림 
print(np.round(arr1))

# 버림 
print(np.trunc(arr1))


[[ 2. -2.]
 [ 3.  4.]]
[[ 1. -3.]
 [ 3.  4.]]
[[ 2. -3.]
 [ 3.  4.]]
[[ 1. -2.]
 [ 3.  4.]]


TypeError: only length-1 arrays can be converted to Python scalars