In [168]:
# Section1-1 n차원 배열(narray) 생성하기 

import numpy as np

# 1차원 배열 
arr = np.array([1,2,3])

print(arr)

# 2차원 배열 
arr2 = np.array([[1,2,3],
                 [4,5,6]])

print(arr2)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [169]:
# numpy arry와 리스트는 다르다. 

type([1,2,3])
type(arr)

numpy.ndarray

In [170]:
# 튜플을 바로 np array로 
tpl = (4,5,6)
arr = np.array(tpl)
print(arr)

# 리스트를 바로 np array로
lst = [1,2,3] 
arr = np.array(lst)
print(arr)

# 리스트로 2차원 array
lst2 = [[1,2,3],[4,5,6]]
arr2 = np.array(lst2)
print(arr2)

[4 5 6]
[1 2 3]
[[1 2 3]
 [4 5 6]]


In [171]:
# shape 각 배열의 차원의 크기 / 제일 중요하다. 
arr1 = np.array([1,2,4])
arr2 = np.array([[1,2,3],[4,5,6]])

print(arr1.shape)
print(arr2.shape)

print(arr1.shape, arr2.shape)

# ndim 차원을 알려준다. 
print(arr1.ndim, arr2.ndim)

# 사이즈는 전체 원소 갯수를 알려준다. 
print(arr1.size, arr2.size)


(3,)
(2, 3)
(3,) (2, 3)
1 2
3 6


In [172]:
# 1-2 N차원 배열의 데이터 타입 

arr1 = np.array([1,2,3], dtype=float)
print(arr1, arr1.dtype)

arr2 = np.array([1.1,2.4,3.7], dtype=int)
print(arr2, arr2.dtype)

# bool 데이터 타입은 0 false, 1 true 
arr3 = np.array([0,1,1,0], dtype=bool)
print(arr3, arr3.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[False  True  True False] bool


In [173]:
# 기존에 있던 데이터 타입을 변형하려면, astype을 쓰면 됩니다. 
# 먼저 1차원 어레이 함 만들어 볼게요. 
arr4 = np.array([0,1,2,3])
print(arr,arr.dtype)

arr = arr.astype(np.float32) # 32로 변경된 것을 볼 수 있습니다. 
print(arr, arr.dtype)

[1 2 3] int32
[1. 2. 3.] float32


In [174]:
# 데이터 타입이 혼재하는 경우 
arr = np.array([1,2,3.4,'45']) # 맨 마지막 데이터 기준으로 데이터 타입이 바뀜. 
print(arr,arr.dtype) # U32는 유니코드 형식으로 바뀌었다는걸 말함. 

arr = np.array([1,2,3.4,'45'], dtype = int) # 데이터 타입을 정수형으로 바꿔봄. 
print(arr,arr.dtype) # 근데 중간 문자열이 진짜 글자면 에러남. 

['1' '2' '3.4' '45'] <U32
[ 1  2  3 45] int32


In [175]:
# 1-3 정해진형식의 n 차원 배열 생성하기 
# np.zeroes()
arr = np.zeros([2,2], dtype= int) # argument로 shape을 넣었다. 2행 2열
print(arr)

# np.ones()
arr = np.ones([3,5], dtype = int)
print(arr)

# np.full() 정해진 숫자로 가득채움. 
arr = np.full((2,3),5, dtype = float)
print(arr)

# np.eye()
arr = np.eye(3,4,k=1, dtype = int)
print(arr)

[[0 0]
 [0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[5. 5. 5.]
 [5. 5. 5.]]
[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [176]:
# np.zeroes_like() 원래의 배열과 동일한 쉐입의 배열을 만들어 보자. 
arr = np.array([[1,2,3],
               [4,5,6]])

# np.zeroes_like()
arr_z = np.zeros_like(arr)
print(arr_z)

# np.ones_like()
arr_z = np.ones_like(arr)
print(arr_z)

# np.full_like()
arr_z = np.full_like(arr,7)
print(arr_z)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[7 7 7]
 [7 7 7]]


In [ ]:
# 1-4 특정범위의 값을 가지는 N차원 배열 생성하기 

In [ ]:
# 1-5 난수로 이루어진 N차원 배열 생성하기 

In [ ]:
# 1-6 Seed값을 통한 난수 생성 제어 