z1 = tensor * tensor와 z2 = tensor.mul(tensor)

In [2]:
# 두가지 방법으로 텐서의 요소별 곱셈을 수행한다. 
# 요소별 곱셈이란, 두 텐서의 같은 위치에 있는 요소끼리 곱한다. 

import torch 

tensor = torch.ones(4,4)

tensor[:,1] = 0

z1 = tensor*tensor
z2 = tensor.mul(tensor)

z1
z2


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\qkim8\AppData\Local\pypoetry\Cache\virtualenvs\torch-project-HfEXwiMh-py3.12\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\Users\qkim8\AppData\Local\pypoetry\Cache\virtualenvs\torch-project-HfEXwiMh-py3.12\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\qkim8\AppData\Local\pypoetr

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

텐서 인덱싱 : 텐서에서 특정 위치의 값을 가져온다. 텐서는 숫자의 배열이고 각 숫자의 위치는 인덱싱이다. 

In [6]:
import torch 

tensor = torch.tensor([[1,2],[3,4]])

element = tensor[0,0]

print(element)

tensor(1)


tensor[0,0]은 첫번째 행의 첫번째 요소를 가져오는 방법이다. 

텐서 슬라이싱은 텐서에서 한번에 여러값을 가져온다. 슬라이싱을 이용하면 특정 범위의 숫자를 가져온다. 

In [7]:
# 슬라이싱 
tensor = torch.tensor([[1,2],[3,4]])
first_column = tensor[:,0]
first_column


tensor([1, 3])

tensor[:,0] 은 모든 행의 첫번째 열을 가져오는 것이다. 

인플레이스 연산은 텐서의 값을 직접 바꾸는 연산이다. 새로운 연산을 만들지 않고 기존의 텐서 값을 바꾼다. 
새로운 텐서를 만들지 않기 때문에 메모리를 절약할 수 있다. 

In [8]:
tensor = torch.tensor([[1,2],[3,4]])
tensor.add_(1)

tensor

tensor([[2, 3],
        [4, 5]])