In [1]:
# 예제 4번 
import numpy as np 
arr = np.arange(2,20,2).reshape((3,3))

#행을 기준으로 3개의 배열로 분할하여 분할
#분할 된 각 배열의 원소들을 제곱한 결과를 다시 원본 배열에 행을 기준으로 병합 하시오 

print("Original array:")
print(arr)

# 행 기준 3개의 배열로 분할 
arr_split = np.split(arr, 3)
print("\nSplit arrays:")
print(arr_split)


# 각 배열의 원소들을 제곱한다. 
answer = []
for sub_arr in arr_split:
    arr_new = sub_arr * sub_arr  # 또는 np.square(sub_arr)
    answer.extend(arr_new)

print(answer)

# 재구성 
result = np.array(answer).reshape(arr.shape)
print("\nResult after squaring and merging:")
print(result)


Original array:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Split arrays:
[array([[2, 4, 6]]), array([[ 8, 10, 12]]), array([[14, 16, 18]])]
[array([ 4, 16, 36]), array([ 64, 100, 144]), array([196, 256, 324])]

Result after squaring and merging:
[[  4  16  36]
 [ 64 100 144]
 [196 256 324]]


In [2]:
arr_vsplit = np.vsplit(arr,3) # row 갯수로 분할 한다. 
print(arr_vsplit)

[array([[2, 4, 6]]), array([[ 8, 10, 12]]), array([[14, 16, 18]])]


In [3]:
# 답 
import numpy as np 
arr = np.arange(2,20,2).reshape((3,3))
print("Original array:")
print(arr)

# vsplit 
s1 = np.vsplit(arr,3)
print("\nApplied split:")
print(s1)

# square 
s2 = np.square(s1) 
print('\nSquared:')
print(s2)

# squeeze
s3 = np.squeeze(s2, axis=1)
print(s3)

# vstack
answer = np.vstack((arr,s3))
print(s3)

Original array:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Applied split:
[array([[2, 4, 6]]), array([[ 8, 10, 12]]), array([[14, 16, 18]])]

Squared:
[[[  4  16  36]]

 [[ 64 100 144]]

 [[196 256 324]]]
[[  4  16  36]
 [ 64 100 144]
 [196 256 324]]
[[  4  16  36]
 [ 64 100 144]
 [196 256 324]]


In [4]:
# 실습예제 5 
# 삼각함수의 특수각 (0,30,60,90)을 numpy.array로 생성 후 
# 특수각에 해당하는 sin, cos, tan값을 각각 구한다. 
# 파이썬 list에 담고 그 후 list 값을 출력하라. 무한대 라면, INF 문자열 출력할 것 . 
# numpy에서 삼각함수는 radian 값을 쓰기 때문에 각을 radian으로 변경해야 한다. 
# degree x Pi // 180 

# 1 특수각을 배열에 넣어준다. 
print('\n특수각 배열에 넣기:')
arr = np.arange(0,91,30)
print(arr)

# 2 파이썬 리스트에 담고, 특수각에 해당하는 sin cos tan 값을 구한다. 이걸 인쇄한다. 
print('\n특수각 리스트에 담기:')
lst = []
lst.append(np.sin(arr*np.pi/180)) # radian으로 변경을 포함한다. 
lst.append(np.cos(arr*np.pi/180))
lst.append(np.tan(arr*np.pi/180))

# 내답코드는 리스트 lst 전체를 한 번에 출력했어. 리스트 형태로 출력되는 것뿐만 아니라, sin, cos, tan의 모든 값을 한꺼번에 묶어서 보여줘.

# 내답 
print('\n내답:')
print(lst)

# 정답 
print('\n정답:')
for value_lst in lst:
    for value in value_lst:
        if value >9999999:
            print('INF')
            continue; # continue는 무한대 값이 나왔을 때 그 이후의 코드를 건너뛰고 다음 반복으로 넘어가는 기능이야.
        print(value) # 이 코드는 무한대가 아닌 경우에만 실행됨
    print()



특수각 배열에 넣기:
[ 0 30 60 90]

특수각 리스트에 담기:

내답:
[array([0.       , 0.5      , 0.8660254, 1.       ]), array([1.00000000e+00, 8.66025404e-01, 5.00000000e-01, 6.12323400e-17]), array([0.00000000e+00, 5.77350269e-01, 1.73205081e+00, 1.63312394e+16])]

정답:
0.0
0.49999999999999994
0.8660254037844386
1.0

1.0
0.8660254037844387
0.5000000000000001
6.123233995736766e-17

0.0
0.5773502691896257
1.7320508075688767
INF



In [5]:
# continue 복습하기 
for i in range(5):
    if i == 2:
        continue  # i가 2일 때는 아래 코드 실행을 건너뛰고, 다음 반복으로 넘어감
    print(i)


0
1
3
4


In [6]:
# 실습예제 6
print('\n0으로 먼저 다 채우기:')
arr = np.zeros((7,7), dtype=int)
print(arr)

print('\n인덱싱을 이용해 2칸 간격으로 1 넣기:')
arr[::2, 1::2] = 1
arr[1::2,::2] = 1
print(arr)

for row in range(7):
    for column in range(7):
        print(arr[row,column], end='') 
    print()


0으로 먼저 다 채우기:
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]

인덱싱을 이용해 2칸 간격으로 1 넣기:
[[0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]]
0101010
1010101
0101010
1010101
0101010
1010101
0101010


In [7]:
# numpy 인덱싱, 슬라이싱 

arr = np.array([10,20,30,40,50])

print(arr[0])

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(arr2d[2,0])
print(arr2d[0,1])

10
7
2


In [8]:
# 1차원 슬라이싱 복습 
arr1d = np.array([0, 1, 2, 3, 4, 5, 6, 7])
print(arr1d[::2]) # 처음 부터 끝까지 2칸씩 건너 뛴다. 

# 2차원 슬라이싱 복습 
# 행과 열을 나누어서 생각한다. start은 행 stop은 열 

arr2d = np.array([[0, 1, 2, 3],
                  [4, 5, 6, 7],
                  [8, 9, 10, 11],
                  [12, 13, 14, 15]])

print(arr2d[::2, 1::2])

[0 2 4 6]
[[ 1  3]
 [ 9 11]]


In [9]:
arr = np.array([[ 0,  1,  2,  3,  4],
                [ 5,  6,  7,  8,  9],
                [10, 11, 12, 13, 14],
                [15, 16, 17, 18, 19],
                [20, 21, 22, 23, 24]])

print(arr[1::2, ::2])

[[ 5  7  9]
 [15 17 19]]


In [10]:
arr = np.array([[ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12],
                [13, 14, 15, 16]])

print(arr[::2, 1::2])

[[ 2  4]
 [10 12]]


In [11]:
arr = np.array([[ 1,  2,  3,  4,  5,  6],
                [ 7,  8,  9, 10, 11, 12],
                [13, 14, 15, 16, 17, 18],
                [19, 20, 21, 22, 23, 24],
                [25, 26, 27, 28, 29, 30],
                [31, 32, 33, 34, 35, 36]])

print(arr[::2, ::2])

[[ 1  3  5]
 [13 15 17]
 [25 27 29]]


In [12]:
# 실습예제 7 
# 두 행렬에 대하여 내적 연산을 수행한 결괏값을 출력하시오 
# 소숫점 제거할 것. 

arr1 = np.array([[2.1,3.5],
                [4.2,2.7],
                [2.3,1.9]])

arr2 = np.array([[5,2,3],
                [1,3,5]])

# 1 내적 연산 = np.dot()answer = np.dot(ar1, ar2)
# 2 브로드 캐스팅 = answer = ar1*ar2
# # 소수점 제거 (잘라내기)
# print(np.trunc(arr))   # [1. 2. 3.]

result = np.dot(arr1, arr2)
print(np.trunc(result))


[[14. 14. 23.]
 [23. 16. 26.]
 [13. 10. 16.]]


In [13]:
# 실습 예제8
# 조건 연산자, Boolean 인덱싱을 이용해 다음 배열 원소들 중 2,5 배수만 추출
# 오름차순으로 정렬해서 2,4 행렬로 수정 



arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

# 내답 
# for i in arr:
    
#     condition = (arr == 2*i) | (arr == 5*i)
#     final = np.sort(condition)
#     print(final)

# final_answer = final.reshape((2,4))

#조건을 만족하는 배열의 값을 추출한 후, 이를 정렬해야 해.
#조건을 만족하는 값을 정렬한 후, 2x4 배열로 재배열해야 해.

# 정답 
# 조건 
condition = (arr % 2 == 0) | (arr % 5 == 0)

# 조건을 만족하는 배열의 값을 추출한 후, 이를 정렬
final = np.sort(arr[condition]) 
# arr[condition]은 Boolean 인덱싱을 사용해, 배열 arr에서 **조건을 만족하는 값(True인 위치의 값)**들만 추출하는 역할을 해. 

# 배열의 크기를 8로 맞추기 (부족한 값을 반복해서 채움)
final_resized = np.resize(final, (2, 4))

print(final_resized)

# np.resize(): 기존 값을 반복해서 배열을 강제로 크기에 맞춰 조정할 수 있어.


[[ 2  4  5  6]
 [ 8 10 12  2]]


In [17]:
# 인강 정답 
print(np.sort(np.append(arr[arr % 2 == 0], arr[arr % 5 == 0])).reshape(2,4))


[[ 2  4  5  6]
 [ 8 10 10 12]]
