In [1]:
# Copyright 2023, Acadential, All rights reserved.

# 2-5. PyTorch 기초 - Tensor

## Tensor란?

Tensor란 데이터를 표현하는 단위로, 다차원 배열의 일반화된 모습입니다. \
PyTorch에서 Tensor을 가지고 연산을 수행하면, 해당 연산은 Computational Graph 상에 표현되고, 나중에 Backward propagation을 통해 Gradient를 계산할 수 있습니다.

## Initializing a tensor

Tensor을 정의하는 방법은 다음과 같습니다.

1. 지정된 값으로 초기화
2. 랜던한 값으로 초기화
3. Numpy array로부터 초기화

In [2]:
# Import related library
import numpy as np
import torch 


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\qkim8\AppData\Local\pypoetry\Cache\virtualenvs\torch-project-HfEXwiMh-py3.12\Lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\Users\qkim8\AppData\Local\pypoetry\Cache\virtualenvs\torch-project-HfEXwiMh-py3.12\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "c:\Users\qkim8\AppData\Local\pypoetr

## 초기화 방법 1: 지정된 값으로 Tensor 초기화

In [3]:

data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [4]:
print(x_data)
x_data

tensor([[1, 2],
        [3, 4]])


tensor([[1, 2],
        [3, 4]])

In [5]:
x_data.dtype # 데이터 타입도 자동으로 유추해준다. 

torch.int64

## 초기화 방법 2: 랜덤한 값으로 Tensor 초기화

In [6]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor : \n {rand_tensor}\n')

print(f'Random Tensor : \n {ones_tensor}\n')

print(f'Random Tensor : \n {zeros_tensor}\n')

Random Tensor : 
 tensor([[0.3056, 0.1811, 0.4117],
        [0.5210, 0.2231, 0.0141]])

Random Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Random Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



## 초기화 방법 3: Numpy 배열로부터 Tensor 초기화

In [ ]:
import numpy as np
import torch

data = [[1, 2], [3, 4]]
np_array = np.array(data, dtype=np.float32)  # 데이터 타입을 명시적으로 설정

# numpy 배열이 연속적인지 확인
np_array = np.ascontiguousarray(np_array)

# numpy 배열을 PyTorch 텐서로 변환
x_np = torch.from_numpy(np_array)

print(x_np)

In [ ]:
x_np.dtype 

# Tensor 데이터의 형식 지정

Tensor의 데이터 형식은 어떤 것들이 있을까요?

1. 정수 int (integer) \
    1-1. ```torch.int8```, ```torch.int16```, ```torch.int32```, ```torch.int64``` (```torch.long```) \
    1-2. ```torch.uint8```: unsigned integer로 양의 정수 0 ~ 255 숫자만 포함, 주로 이미지 데이터를 다룰 때 사용.
2. float \
    2-1. ```torch.float16```, ```torch.float32```, ```torch.float64``` 
3. boolean: ```torch.bool```
4. etc.



### torch.float32 형식으로 초기화

In [9]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data, dtype = torch.float32)

In [10]:
x_data

tensor([[1., 2.],
        [3., 4.]])

In [11]:
x_data.dtype

torch.float32

### torch.uint8 형식으로 초기화

In [12]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data, dtype = torch.unit8)

AttributeError: module 'torch' has no attribute 'unit8'

In [13]:
x_data.dtype

torch.float32

### 다른 dtype으로 변환

In [14]:
x_data = x_data.to(torch.float16)

In [15]:
x_data.dtype

torch.float16

# 다른 Device로 Tensor 옮기기

1. GPU가 사용가능한지 확인하기
2. 다른 Device로 Tensor 옮기기
3. 어떤 Device상에 Tensor가 있는지 확인하기

### GPU가 사용가능한지 확인하기

In [16]:
torch.cuda.is_available()

False

### GPU로 Tensor 옮기기

In [18]:
tensor = tensor.to("cuda")

NameError: name 'tensor' is not defined

### CPU로 Tensor 옮기기

In [20]:
x_data = x_data.cpu()
x_data = x_data.to("cpu")

### 어떤 Device상에 Tensor가 있는지 확인하기

In [21]:
x_data.device

device(type='cpu')

# Tensor을 활용한 연산

1. Indexing and slicing
2. Concatenation
3. Arithmetric
4. Inplace-operation

### Indexing 

In [24]:
tensor = torch.ones(4,4)

In [28]:
print(f'first row: {tensor [0]}')
print(f'first column: {tensor [:,0]}')
print(f'last column: {tensor [:,-1]}')

tensor[:,1] = 0
print(tensor)

first row: tensor([1., 1., 1., 1.])
first row: tensor([1., 1., 1., 1.])
first row: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Concatenation

In [29]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1 )
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

### Arithmetric

In [34]:
# 행렬의 곱 예제 # T는 전치 행렬을 수행한다. 
y1 = tensor @ tensor.T
y1

y2 = tensor.matmul(tensor.T)
y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [36]:
# elemental wise 곱셈 
z1 = tensor * tensor 
z2 = tensor.mul(tensor )

z1
z2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

### Inplace operation

In [37]:
tensor 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [38]:
tensor.add_(5)
tensor

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])