In [16]:
import numpy as np
# N차원 배열의 형태 변경 
# 5-1 배열의 형태 변경 reshape()
arr = np.arange(12)
print(arr,arr.ndim)

arr = arr.reshape((3,4)) # 사이즈 안맞으면 reshape 함수 못쓴다. 
print(arr)

arr = arr.reshape(2,3,2) # 3차원으로 프린트 
print(arr, arr.ndim)

arr = arr.reshape(2,2,1,3) # 4차원으로 프린트 
print(arr, arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 3
[[[[ 0  1  2]]

  [[ 3  4  5]]]


 [[[ 6  7  8]]

  [[ 9 10 11]]]] 4


In [17]:
# Curse of Dimensionality 
# 차원이 증가하면서 학습 데이터 수가 차원의 수보다 적어지면서 모델의 성능이 적어지는 현상 

In [18]:
# 5-2 배열의 형태 변경 resize(), ravel()
arr = np.arange(12)
print(arr)

arr.resize(3,4)
print(arr)

arr = arr.ravel() # 1차원으로 변경해주는 함수임. 
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [19]:
arr = np.arange(1,13)
print(arr)

arr = arr.reshape(3,-1) # -1이 들어가면 shape값이 자동으로 계산이 됨. 3은 행값
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
# 5-3 배열의 형태 변경 expand_dims(), squeeze()
# expand_dims() 입력한 axis 기준으로 차원을 추가하는 함수이다. 
arr = np.array([1,2])
print(arr, arr.shape)

arr = np.expand_dims(arr, axis = 1)
print(arr, arr.shape)


arr = np.expand_dims(arr, axis = 0)
print(arr, arr.shape)

[1 2] (2,)
[[1]
 [2]] (2, 1)
[[[1]
  [2]]] (1, 2, 1)


In [23]:
# squeeze() # expand_dims의 반대로 차원 줄이는거임. 
arr = np.array([[1,2]])
print(arr, arr.shape, arr.ndim)
arr = np.squeeze(arr, axis = 0)
print(arr)


[[1 2]] (1, 2) 2
[1 2]


In [36]:
arr = np.array([[[1],
                [2],
                [3]]])

print(arr, arr.shape, arr.ndim)

arr = np.squeeze(arr, axis = 0)
print(arr, arr.shape, arr.ndim)


arr = np.squeeze(arr, axis = 1)
print(arr, arr.shape, arr.ndim)

[[[1]
  [2]
  [3]]] (1, 3, 1) 3
[[1]
 [2]
 [3]] (3, 1) 2
[1 2 3] (3,) 1


In [38]:
arr = np.array([[[1,2,3]]])
print(arr, arr.shape, arr.ndim)

arr = np.squeeze(arr, axis = 1)
print(arr, arr.shape, arr.ndim )

# axis 입력안하면, 행렬이든 텐서든 1차원으로 축소하게됨. 

[[[1 2 3]]] (1, 1, 3) 3
[[1 2 3]] (1, 3) 2


In [40]:
# 5-4 전치행렬(Transpose Matrix) 
arr = np.array([[1,2],
                [3,4]])

print(arr.T)

[[1 3]
 [2 4]]


In [42]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

print(arr.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [43]:
arr = np.array([[1,2],
                [3,4],
                [5,6]])
print(arr.T)

[[1 3 5]
 [2 4 6]]


In [ ]:
arr = np.array([[1,2],
                [3,4],
                [5,6]])
# quiz 왜 에러가 날까. 

arr2 = np.full((3,2),2)
print(arr.dot(arr2))

# 답 
print((arr.T).dot(arr2))