In [10]:
# 실습 예제 1 
# 원소가 모두 3인(3,4,5) 형태의 numpy.array를 출력하라 
import numpy as np
arr = np.full((3,4,5),3, dtype =int) # 3이 차원 4가 열, 5가 행 
print(arr)

[[[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]]


In [16]:
# 실습 예제 2
# 정수 -50 ~50 범위안의 난수로 이뤄진 
# (4,5) 형태의 numpy.array를 출력하고 
# 행 기준 오름차순 정렬 결과와 
# 1차원 배열로 변경하여 오름 차순 정렬한 결과 출력해라 


# 랜덤한 정수만 출력하는 함수 
# np.random.randint()
arr = np.random.randint(-50,50,(4,5)) # hyper parameter는 반드시 1개 이상 작성
print(np.sort(arr, axis = 0)) # 행 기준은 axis 0 임. 
print(np.sort(arr, axis = None))


[[-44  -2 -29 -20 -28]
 [ 12  11  -9 -14 -19]
 [ 15  33   5  -3 -17]
 [ 25  48  44  46  35]]
[-44 -29 -28 -20 -19 -17 -14  -9  -3  -2   5  11  12  15  25  33  35  44
  46  48]


In [23]:
# 실습 예제 3
# 평균값, 표준편차, 중앙값을 순서대로 구하여 구한 순서대로 원소가 이루어진 새로운 list를 구성하고 출력해라. 

py_list = [
    np.full(3,8),
    np.array([33,-15,26]),
    np.linspace(17,26,3)
]

print(py_list)


# 내답
mean = np.mean(py_list, axis = None)
print(mean)

std = np.std(py_list)
print(std)

median = np.median(py_list, axis = None)
print(median)

# 정답 
answer = []
for i in py_list:
    answer.append(np.mean(i))
    answer.append(np.std(i))
    answer.append(np.median(i))
print(answer)

[array([8, 8, 8]), array([ 33, -15,  26]), array([17. , 21.5, 26. ])]
14.722222222222221
13.57512248995507
17.0
[8.0, 0.0, 8.0, 14.666666666666666, 21.171259344267224, 26.0, 21.5, 3.6742346141747673, 21.5]


In [ ]:
# 내답이 틀린 이유는 py_list에 있는 여러 배열들의 mean, std, median을 구했어야하는데 전체를 퉁쳤기 때문. 