In [3]:
import numpy as np
# 1차원 배열 정렬 
# 정렬: 오름차순, 내림차순 등 대소관계에 따라 나열하는 일 
arr = np.random.randint(10, size = 10)
print(arr)

print(np.sort(arr))
print(np.sort(arr)[::-1]) # : 처음부터 : 끝까지 -1 뒤로부터 한칸간격으로 출력 # 이거는 근데 원본을 수정한것이 아니다. 

arr.sort() # 이렇게 하면 원본이 수정된다. 

[5 1 0 0 3 0 9 8 8 1]
[0 0 0 1 1 3 5 8 8 9]
[9 8 8 5 3 1 1 0 0 0]


In [4]:
# 2차원 배열 
arr = np.random.randint(15, size = (3,4))
print(arr)

[[ 4 10 14  3]
 [ 6  0  6  9]
 [ 6 10  3  3]]


In [9]:
print(np.sort(arr, axis = 0))
print(np.sort(arr, axis = None)) # NONE이면 1차원으로 변경을 해서 오름차순으로 정렬하게 됨. 

[[ 4  0  3  3]
 [ 6 10  6  3]
 [ 6 10 14  9]]
[ 0  3  3  3  4  6  6  6  9 10 10 14]


In [11]:
# argsort()
# 원소가 정렬이 되었을 떄, 정렬된 원소의 원래 배열에서의 인덱스를 반환함. 
print(np.sort(arr, axis = 1))
print(np.argsort(arr, axis=1))
print(np.argsort(arr, axis=0))

# axis 0은 열기준으로 1은 행 기준으로 본다. 

[[ 3  4 10 14]
 [ 0  6  6  9]
 [ 3  3  6 10]]
[[3 0 1 2]
 [1 0 2 3]
 [2 3 0 1]]
[[0 1 2 0]
 [1 0 1 2]
 [2 2 0 1]]
