In [5]:
# 배열에 원소 추가 및 삭제  

import numpy as np 

# python list 
arr = [1,2,3,4,5,6,7,8]
arr.insert(2,50)
print(arr)

# 1차원 배열 
arr = np.arange(1,9)
arr = np.insert(arr,2,50)
print(arr)

[1, 2, 50, 3, 4, 5, 6, 7, 8]
[ 1  2 50  3  4  5  6  7  8]


In [12]:
# 2차원 배열 
arr = np.arange(1,13).reshape(3,4)
print(arr)

arr = np.insert(arr,2,50, axis = 0)
print(arr)

arr = np.insert(arr,2,50, axis = 1)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [50 50 50 50]
 [ 9 10 11 12]]
[[ 1  2 50  3  4]
 [ 5  6 50  7  8]
 [50 50 50 50 50]
 [ 9 10 50 11 12]]


In [13]:
# delete 
arr = np.arange(1,13).reshape(3,4)
print(arr)

arr = np.delete(arr, 2, axis = 0)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]


In [19]:
# 배열간의 병합 : 두개의 병합 합치기 
# append : 마지막에 추가 

# 2차원 배열 

arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(1,13).reshape(3,4)
print(arr1)
print(arr2, end = '\n\n')

# axis 0 
arr3 = np.append(arr1, arr2, axis = 0)
print(arr3, end = '\n\n')

# axis 1
arr3 = np.append(arr1, arr2, axis = 1)
print(arr3, end = '\n\n')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4  1  2  3  4]
 [ 5  6  7  8  5  6  7  8]
 [ 9 10 11 12  9 10 11 12]]



In [22]:
# vstack(), hstack()
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)

print(arr1)
print(arr2, end = '\n\n')

arr3 = np.vstack((arr1,arr2))
print(arr3)

arr4 = np.hstack((arr1, arr2))
print(arr4)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [23]:
# concatenate
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)
arr3 = np.concatenate([arr1,arr2], axis =0)
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
# 배열의 분할 
# 2차원 배열의 분할 
arr = np.arange(1,13).reshape(3,4)

# vsplit -> axis=0
arr_vsplit = np.vsplit(arr,3) # row 갯수로 분할 한다. 
print(arr_vsplit)

# hsplit -> axis=1
arr_hsplit = np.hsplit(arr,2)
print(arr_hsplit)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [33]:
# 3차원 배열의 분할 

arr = np.random.randint(0,10,(4,6,8))
print(arr)

[[[0 5 9 4 6 1 0 4]
  [2 8 7 4 8 2 9 0]
  [6 6 2 6 4 8 5 9]
  [7 5 8 4 4 6 4 2]
  [1 5 2 2 5 1 9 3]
  [7 1 0 7 4 7 6 2]]

 [[4 8 4 3 8 8 7 5]
  [6 0 9 2 4 5 8 1]
  [2 5 4 1 6 5 9 3]
  [0 0 6 1 8 9 8 8]
  [2 2 7 8 4 2 2 7]
  [9 8 3 9 0 6 2 0]]

 [[7 5 2 8 4 6 5 3]
  [9 3 2 1 5 2 2 5]
  [3 6 3 7 7 7 5 0]
  [4 8 6 9 9 9 3 5]
  [2 9 2 1 9 3 2 8]
  [9 7 6 9 2 7 6 2]]

 [[5 8 8 3 9 0 0 0]
  [2 5 5 4 7 0 1 4]
  [2 8 0 7 0 4 7 2]
  [3 0 9 5 3 4 2 8]
  [9 4 9 2 9 8 9 3]
  [5 5 6 5 9 9 6 7]]]


In [34]:
arr_vsplit = np.vsplit(arr,2)
print(arr_vsplit)

[array([[[0, 5, 9, 4, 6, 1, 0, 4],
        [2, 8, 7, 4, 8, 2, 9, 0],
        [6, 6, 2, 6, 4, 8, 5, 9],
        [7, 5, 8, 4, 4, 6, 4, 2],
        [1, 5, 2, 2, 5, 1, 9, 3],
        [7, 1, 0, 7, 4, 7, 6, 2]],

       [[4, 8, 4, 3, 8, 8, 7, 5],
        [6, 0, 9, 2, 4, 5, 8, 1],
        [2, 5, 4, 1, 6, 5, 9, 3],
        [0, 0, 6, 1, 8, 9, 8, 8],
        [2, 2, 7, 8, 4, 2, 2, 7],
        [9, 8, 3, 9, 0, 6, 2, 0]]]), array([[[7, 5, 2, 8, 4, 6, 5, 3],
        [9, 3, 2, 1, 5, 2, 2, 5],
        [3, 6, 3, 7, 7, 7, 5, 0],
        [4, 8, 6, 9, 9, 9, 3, 5],
        [2, 9, 2, 1, 9, 3, 2, 8],
        [9, 7, 6, 9, 2, 7, 6, 2]],

       [[5, 8, 8, 3, 9, 0, 0, 0],
        [2, 5, 5, 4, 7, 0, 1, 4],
        [2, 8, 0, 7, 0, 4, 7, 2],
        [3, 0, 9, 5, 3, 4, 2, 8],
        [9, 4, 9, 2, 9, 8, 9, 3],
        [5, 5, 6, 5, 9, 9, 6, 7]]])]


In [35]:
arr_vsplit = np.hsplit(arr,2)
print(arr_vsplit)

[array([[[0, 5, 9, 4, 6, 1, 0, 4],
        [2, 8, 7, 4, 8, 2, 9, 0],
        [6, 6, 2, 6, 4, 8, 5, 9]],

       [[4, 8, 4, 3, 8, 8, 7, 5],
        [6, 0, 9, 2, 4, 5, 8, 1],
        [2, 5, 4, 1, 6, 5, 9, 3]],

       [[7, 5, 2, 8, 4, 6, 5, 3],
        [9, 3, 2, 1, 5, 2, 2, 5],
        [3, 6, 3, 7, 7, 7, 5, 0]],

       [[5, 8, 8, 3, 9, 0, 0, 0],
        [2, 5, 5, 4, 7, 0, 1, 4],
        [2, 8, 0, 7, 0, 4, 7, 2]]]), array([[[7, 5, 8, 4, 4, 6, 4, 2],
        [1, 5, 2, 2, 5, 1, 9, 3],
        [7, 1, 0, 7, 4, 7, 6, 2]],

       [[0, 0, 6, 1, 8, 9, 8, 8],
        [2, 2, 7, 8, 4, 2, 2, 7],
        [9, 8, 3, 9, 0, 6, 2, 0]],

       [[4, 8, 6, 9, 9, 9, 3, 5],
        [2, 9, 2, 1, 9, 3, 2, 8],
        [9, 7, 6, 9, 2, 7, 6, 2]],

       [[3, 0, 9, 5, 3, 4, 2, 8],
        [9, 4, 9, 2, 9, 8, 9, 3],
        [5, 5, 6, 5, 9, 9, 6, 7]]])]
