In [35]:
# N차원 배열의 인덱싱 
# 2-1 배열의 index 접근하기 
import numpy as np

arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr = np.arange(10)
print(arr)

print(arr[3])
print(arr[1])
print(arr[-1])
print(arr[-3])

[0 1 2 3 4 5 6 7 8 9]
3
1
9
7


In [ ]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

print(arr, arr.shape, arr.ndim)
print(arr[0][3]) # 첫번째가 행이고 두번째가 열이여서 [], []
print(arr[0,3])
print(arr[0])
print(arr[0,:]) # 첫째 행 다 부를거니까 모든 열을 다 포함시킨 상태인 거임. 
print(arr[:,1]) # 행은 다 포함시킨 상태인 거임. 

print(arr[:2,2:])

In [ ]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

print(arr[:2,2:]) # 다시 확인 하기 

In [43]:
# N차원 배열의 인덱싱 
# 2-2 Fancy 인덱싱 : 특정 인덱스를 여러개를 선택을 해서 탐색함. 

# 1차원 배열 
arr = np.array([5,2,'s',4,4])
print(arr[[0,2,4]])

# 2차원 배열 
arr = np.array([[5,10,15,20],
                [25,30,35,40],
                [45,50,55,60]])
print(arr[[0,2],2:])
print(arr[1:,[2,3]])

['5' 's' '4']
[[15 20]
 [55 60]]
[[35 40]
 [55 60]]


In [45]:
# N차원 배열의 인덱싱 
# 2-3 Boolean 인덱싱 : 트루 폴스를 이용해서 배열을 탐색하는 방법이다. 
arr = np.array([1,2,3,4])
print(arr[[True, False, True, False]]) # 갯수 맞춰서 boolean 작성해야 함. 

[1 3]


In [46]:
# 2차원 어레이에서의 불리언 
arr = np.array([[1,2,3,4],
                [5,6,7,8]])

print(arr[[True, False],True])

[[1 2 3 4]]


In [49]:
# 조건 연산자를 이용해 가져오기 
arr = np.array([[1,2,3,4],
                [5,6,7,8]])

print(arr[arr>5])

[6 7 8]
