In [18]:
import numpy as np
# N차원 배열 연산법 
# 배열의 연산 

# 3-3 배열의 연산 / min/ max/ sum/ mean / std/ cumsum/ median

# 2차원 행렬 

arr1 = np.array([[1,2],
                [3,4]])

arr2 = np.array([[2,2],
                [2,2]])

# min max 
print(np.min(arr1))
print(arr1.min())
print(arr1.min(axis=0)) # 엑시스가 이해가 안가 개념을 쉽게 이해시켜줘 
print(np.max(arr1))




1
1
[1 2]
4


axis=0: 행을 따라(세로 방향) 계산한다는 뜻이야. 각 열에 대해 연산을 수행해.  
axis=1: 열을 따라(가로 방향) 계산한다는 뜻이야. 각 행에 대해 연산을 수행해.  

In [19]:
# sum
print(np.sum(arr1))
print(arr1.sum(axis=0))

10
[4 6]


In [20]:
# mean 
print(np.mean(arr1))
print(arr1.mean())
print(arr1.mean(axis = 0))
print(arr1.mean(axis = 1))

2.5
2.5
[2. 3.]
[1.5 3.5]


In [21]:
# std 표준편차값 
print(np.std(arr1)) 
# 값들이 평균에서 얼마나 흩어져 있는지를 나타내. 
# 값들이 평균에서 멀리 떨어져 있으면 표준편차가 크고, 
# 값들이 평균에 가까우면 표준편차가 작아.

1.118033988749895


In [22]:
# cumsum 누적합수를 계산하는 함수 
print(np.cumsum(arr1))
print(arr1.cumsum(axis = 0)) 
# cumsum([1, 2, 3, 4]) = [1, (1+2), (1+2+3), (1+2+3+4)] = [1, 3, 6, 10]

[ 1  3  6 10]
[[1 2]
 [4 6]]


In [25]:
# median()
arr1 = np.array([[1,2],
                [3,4]])

arr2 = np.array([[2,2],
                [2,2]])

print(np.median(arr1, axis = 0)) 
# 배열을 작은 값부터 큰 값으로 정렬했을 때 중간에 위치한 값을 뜻해.

[2. 3.]


In [29]:
# 브로드캐스팅 
arr1 = np.array([[0,0,0],
                 [1,2,3]])

arr2 = np.array([[1,1,1]])

print(arr1 + arr2)

arr1 = np.array([[1,1,1]])
arr2 = np.array([[1],
                 [2],
                 [3]])
print(arr1 + arr2)

[[1 1 1]
 [2 3 4]]
[[2 2 2]
 [3 3 3]
 [4 4 4]]


In [32]:
# 벡터 연산의 장점 : 시간 많이 아낄 수 있으니까 이번엔 time 패키지 불러와서 비교해보자 

import time  
arr = np.arange(999999)
print(arr)

# for 
sum = 0;
before = time.time()
for i in arr:
    sum += i
after = time.time()
print(sum, after-before,'초')

[     0      1      2 ... 999996 999997 999998]
1782293665 0.057558298110961914 초


C:\Users\82106\AppData\Local\Temp\ipykernel_38868\836014617.py:11: RuntimeWarning: overflow encountered in scalar add
  sum += i


In [33]:
# vector 연산 
before = time.time()
sum = np.sum(arr)
after = time.time()
print(sum, after - before , '초')

1782293665 0.0 초


In [35]:
# 새로운 비교 
arr1 = np.arange(999)
arr2 = np.arange(999)

# for 
sum = 0 
before = time.time()
for i,j in zip(arr1,arr2):
    sum += i*j
after = time.time()
print(sum, after - before, '초')

# 벡터 연산 
before = time.time()
sum = np.dot(arr1, arr2)
after = time.time()
print(sum, after-before, '초')


331835499 0.0 초
331835499 0.0 초
